// export const CREATE_NEW_POST='CREATE_NEW_POST';
export const GET_ALL_POST='GET_ALL_POST';
export const GET_ALL_POST_LOADING='GET_ALL_POST_LOADING';
export const GET_ALL_POST_FAILED='GET_ALL_POST_FAILED';

// export const CREATE_NEW_POST='CREATE_NEW_POST';